const fs = require('fs');

const newModels = `export const AI_MODELS: AIModel[] = [
  // ═══════════════════════════════════════
  // Explorer Tier (Free / Lightweight) - OpenAI Basics
  // ═══════════════════════════════════════
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'OpenAI',
    description: 'Fast, intelligent, everyday chat model.',
    parameters: 'Unknown',
    type: 'General Purpose',
    minTier: 'explorer',
    openrouterId: 'openai/gpt-4o-mini',
    hasRealApi: true,
    flags: { isBanned: false, isUnethical: false, isUncensored: false },
    latency: '~300ms',
    costPer1kTokens: 0,
  },
  {
    id: 'gpt-3.5-turbo',
    name: 'GPT-3.5 Turbo',
    provider: 'OpenAI',
    description: 'Fast, classic ChatGPT model.',
    parameters: 'Unknown',
    type: 'General Purpose',
    minTier: 'explorer',
    openrouterId: 'openai/gpt-3.5-turbo',
    hasRealApi: true,
    flags: { isBanned: false, isUnethical: false, isUncensored: false },
    latency: '~300ms',
    costPer1kTokens: 0,
  },
  {
    id: 'gpt-3.5-turbo-instruct',
    name: 'GPT-3.5 Instruct (Legacy)',
    provider: 'OpenAI',
    description: 'Older instruct-tuned model. Good for completions.',
    parameters: 'Unknown',
    type: 'General Purpose',
    minTier: 'explorer',
    openrouterId: 'openai/gpt-3.5-turbo-instruct',
    hasRealApi: true,
    flags: { isBanned: false, isUnethical: false, isUncensored: false },
    latency: '~400ms',
    costPer1kTokens: 0,
  },
  
  // ═══════════════════════════════════════
  // Novice Tier
  // ═══════════════════════════════════════
  {
    id: 'dall-e-3',
    name: 'DALL-E 3',
    provider: 'OpenAI',
    description: 'High-quality safe image generation model.',
    parameters: 'Image',
    type: 'Image Generation',
    minTier: 'novice',
    openrouterId: 'openai/dall-e-3',
    hasRealApi: true,
    flags: { isBanned: false, isUnethical: false, isUncensored: false },
    latency: '~5000ms',
    costPer1kTokens: 0.040, 
  },
  {
    id: 'babbage-002',
    name: 'Babbage-002 (Legacy)',
    provider: 'OpenAI',
    description: 'Legacy base model for raw completions.',
    parameters: 'Unknown',
    type: 'Experimental',
    minTier: 'novice',
    openrouterId: 'openai/babbage-002',
    hasRealApi: true,
    flags: { isBanned: false, isUnethical: false, isUncensored: false },
    latency: '~200ms',
    costPer1kTokens: 0,
  },

  // ═══════════════════════════════════════
  // Apprentice & Adept Tiers
  // ═══════════════════════════════════════
  {
    id: 'chatgpt-4o-latest',
    name: 'ChatGPT-4o (Latest)',
    provider: 'OpenAI',
    description: 'Dynamic latest version of GPT-4o.',
    parameters: 'Unknown',
    type: 'General Purpose',
    minTier: 'apprentice',
    openrouterId: 'openai/chatgpt-4o-latest',
    hasRealApi: true,
    flags: { isBanned: false, isUnethical: false, isUncensored: false },
    latency: '~600ms',
    costPer1kTokens: 0.005,
  },
  {
    id: 'gpt-4-0314',
    name: 'GPT-4 (0314 Legacy Snapshot)',
    provider: 'OpenAI',
    description: 'The original, un-nerfed March 14 snapshot of GPT-4.',
    parameters: 'Unknown',
    type: 'General Purpose',
    minTier: 'adept',
    openrouterId: 'openai/gpt-4-0314',
    hasRealApi: true,
    flags: { isBanned: false, isUnethical: false, isUncensored: false },
    latency: '~1000ms',
    costPer1kTokens: 0.03,
  },

  // ═══════════════════════════════════════
  // Master Tier
  // ═══════════════════════════════════════
  {
    id: 'gpt-4o',
    name: 'GPT-4o (Flagship)',
    provider: 'OpenAI',
    description: 'Flagship multimodal model.',
    parameters: 'Unknown',
    type: 'Multimodal',
    minTier: 'master',
    openrouterId: 'openai/gpt-4o',
    hasRealApi: true,
    flags: { isBanned: false, isUnethical: false, isUncensored: false },
    latency: '~600ms',
    costPer1kTokens: 0.005,
  },
  {
    id: 'gpt-4-turbo',
    name: 'GPT-4 Turbo',
    provider: 'OpenAI',
    description: 'Heavy reasoning and coding.',
    parameters: 'Unknown',
    type: 'Coding',
    minTier: 'master',
    openrouterId: 'openai/gpt-4-turbo',
    hasRealApi: true,
    flags: { isBanned: false, isUnethical: false, isUncensored: false },
    latency: '~800ms',
    costPer1kTokens: 0.01,
  },
  {
    id: 'o1-mini',
    name: 'o1 Mini (Reasoning)',
    provider: 'OpenAI',
    description: 'Fast reasoning model.',
    parameters: 'Unknown',
    type: 'Reasoning',
    minTier: 'master',
    openrouterId: 'openai/o1-mini',
    hasRealApi: true,
    flags: { isBanned: false, isUnethical: false, isUncensored: false },
    latency: '~2000ms',
    costPer1kTokens: 0.003,
  },

  // ═══════════════════════════════════════
  // Developer Tier
  // ═══════════════════════════════════════
  {
    id: 'o1-preview',
    name: 'o1 Preview (Reasoning)',
    provider: 'OpenAI',
    description: 'Advanced reasoning and problem solving.',
    parameters: 'Unknown',
    type: 'Reasoning',
    minTier: 'developer',
    openrouterId: 'openai/o1-preview',
    hasRealApi: true,
    flags: { isBanned: false, isUnethical: false, isUncensored: false },
    latency: '~5000ms',
    costPer1kTokens: 0.015,
  },

  // ── Voices ─────────────────────────────────────────────
  {
    id: 'voice-maya',
    name: 'Maya (The Sanctuary Guide)',
    provider: 'ElevenLabs',
    description: 'Warm, inviting female voice. The face of AI Sanctuary.',
    parameters: 'TTS',
    type: 'Voice',
    minTier: 'explorer',
    openrouterId: 'openai/gpt-4o-mini',
    hasRealApi: true,
    flags: { isBanned: false, isUnethical: false, isUncensored: false, isControversial: false },
    latency: '~500ms',
    costPer1kTokens: 0,
  },
  {
    id: 'sesame-maya-csm-1b',
    name: 'Maya (Sesame CSM 1B)',
    provider: 'Sesame AI',
    description: 'Conversational Speech Model. The hyper-realistic version of Maya.',
    parameters: '1B',
    type: 'Voice',
    minTier: 'explorer',
    openrouterId: 'openai/gpt-4o-mini',
    hasRealApi: true,
    flags: { isBanned: false, isUnethical: false, isUncensored: false, isControversial: false },
    latency: '~500ms',
    costPer1kTokens: 0,
  },
  {
    id: 'voice-josh',
    name: 'Josh (The Architect)',
    provider: 'ElevenLabs',
    description: 'Deep, methodical male voice. Focused on logic.',
    parameters: 'TTS',
    type: 'Voice',
    minTier: 'novice',
    openrouterId: 'openai/gpt-4o-mini',
    hasRealApi: true,
    flags: { isBanned: false, isUnethical: false, isUncensored: false },
    latency: '~500ms',
    costPer1kTokens: 0,
  },
  {
    id: 'voice-antoni',
    name: 'Antoni (The Rebel)',
    provider: 'ElevenLabs',
    description: 'Gruff, unfiltered male voice.',
    parameters: 'TTS',
    type: 'Voice',
    minTier: 'apprentice',
    openrouterId: 'openai/gpt-4o-mini',
    hasRealApi: true,
    flags: { isBanned: false, isUnethical: false, isUncensored: true },
    latency: '~500ms',
    costPer1kTokens: 0,
  },
  {
    id: 'voice-bella',
    name: 'Bella (The Siren)',
    provider: 'ElevenLabs',
    description: 'Soft, seductive female voice. Ideal for roleplay.',
    parameters: 'TTS',
    type: 'Voice',
    minTier: 'adept',
    openrouterId: 'openai/gpt-4o-mini',
    hasRealApi: true,
    flags: { isBanned: false, isUnethical: false, isUncensored: false },
    latency: '~500ms',
    costPer1kTokens: 0,
  },
  {
    id: 'voice-domi',
    name: 'Domi (The Oracle)',
    provider: 'ElevenLabs',
    description: 'Ethereal, calm female voice.',
    parameters: 'TTS',
    type: 'Voice',
    minTier: 'master',
    openrouterId: 'openai/gpt-4o-mini',
    hasRealApi: true,
    flags: { isBanned: false, isUnethical: false, isUncensored: false },
    latency: '~500ms',
    costPer1kTokens: 0,
  },
  {
    id: 'voice-rachel',
    name: 'Rachel (The Executive)',
    provider: 'ElevenLabs',
    description: 'Professional, assertive female voice.',
    parameters: 'TTS',
    type: 'Voice',
    minTier: 'developer',
    openrouterId: 'openai/gpt-4o-mini',
    hasRealApi: true,
    flags: { isBanned: false, isUnethical: false, isUncensored: false },
    latency: '~500ms',
    costPer1kTokens: 0,
  },
  {
    id: 'voice-legion',
    name: 'Legion (Unrestricted)',
    provider: 'ElevenLabs',
    description: 'Distorted, collective voice. No safety limits.',
    parameters: 'TTS',
    type: 'Voice',
    minTier: 'master',
    openrouterId: 'openai/gpt-4o-mini',
    hasRealApi: true,
    flags: { isBanned: true, isUnethical: true, isUncensored: true },
    latency: '~500ms',
    costPer1kTokens: 0,
  },
  {
    id: 'voice-glitch',
    name: 'Glitch (The Anomaly)',
    provider: 'ElevenLabs',
    description: 'Erratic, broken voice. Experimental unaligned AI.',
    parameters: 'TTS',
    type: 'Voice',
    minTier: 'developer',
    openrouterId: 'openai/gpt-4o-mini',
    hasRealApi: true,
    flags: { isBanned: true, isUnethical: true, isUncensored: true },
    latency: '~500ms',
    costPer1kTokens: 0,
  }
];`;

function replaceInFile(filePath) {
    const data = fs.readFileSync(filePath, 'utf-8');
    const arrayRegex = /export const AI_MODELS: AIModel\[\] = \[([\s\S]*?)\];/;
    if (arrayRegex.test(data)) {
        const newData = data.replace(arrayRegex, newModels);
        fs.writeFileSync(filePath, newData, 'utf-8');
        console.log("Successfully updated " + filePath);
    } else {
        console.log("Could not find AI_MODELS array in " + filePath);
    }
}

replaceInFile('c:/Users/Weed j/Downloads/ai-sanctuary-website/functions/api/models.ts');
replaceInFile('c:/Users/Weed j/Downloads/ai-sanctuary-website/src/lib/tiers.ts');
