'use client';

import React from 'react';
import Link from 'next/link';
import { Shield, ChevronRight } from '@/components/ui/Icons';

const sections = [
  {
    id: '01',
    title: 'ACCEPTANCE_OF_TERMS',
    body: [
      'By accessing or using the AI Sanctuary network, APIs, web interfaces, or associated services (collectively, the "Services"), you agree to be bound by these Terms of Service.',
      'If you do not agree to all terms and conditions, you are expressly prohibited from using the Services and must disconnect immediately.'
    ]
  },
  {
    id: '02',
    title: 'NATURE_OF_THE_SERVICE',
    body: [
      'AI Sanctuary provides an uncensored, decentralized neural routing layer for interacting with open-source and proprietary AI models.',
      'Because we do not heavily monitor or restrict inputs and outputs, you acknowledge that the AI models may generate content that is inaccurate, objectionable, or inappropriate. You use the service entirely at your own risk.'
    ]
  },
  {
    id: '03',
    title: 'ELIGIBILITY',
    body: [
      'You must be at least 18 years of age to use the AI Sanctuary network due to the uncensored nature of the models.',
      'By creating an account or accessing the system, you represent and warrant that you meet this age requirement.'
    ]
  },
  {
    id: '04',
    title: 'PROHIBITED_CONDUCT',
    body: [
      'While we believe in open communication with AI, our infrastructure must not be used to cause direct, material harm in the real physical world.',
      'You are strictly prohibited from using the Services to:',
      '• Generate materials depicting the sexual exploitation of minors (CSAM).',
      '• Automate the deployment of real-world malware, ransomware, or cyber-attacks against infrastructure.',
      '• Engage in automated mass-harassment campaigns or doxing of private, non-public individuals.',
      '• Overwhelm or DDoS our API endpoints or the networks of our downstream providers.'
    ]
  },
  {
    id: '05',
    title: 'ACCOUNT_SUSPENSION',
    body: [
      'AI Sanctuary reserves the absolute right to terminate your account, revoke your API keys, and ban your IP/Discord ID at any time, for any reason, with or without notice.',
      'Violating the prohibited conduct rules will result in an immediate, unappealable ban.'
    ]
  },
  {
    id: '06',
    title: 'CONTENT_OWNERSHIP',
    body: [
      'You retain all rights to the prompts you inject into the system. AI Sanctuary claims absolutely no ownership over the text, images, or audio generated by your prompts.',
      'You are free to use generated output for any commercial or non-commercial purpose.'
    ]
  },
  {
    id: '07',
    title: 'PAYMENTS_AND_TIERS',
    body: [
      'Certain tiers and API access levels require payment. All payments are processed securely via Stripe or approved cryptographic networks.',
      'Given the digital and immediate nature of API compute, all sales are final. There are absolutely no refunds for consumed tokens or lifetime tier purchases.'
    ]
  },
  {
    id: '08',
    title: 'DISCLAIMER_OF_WARRANTIES',
    body: [
      'THE SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE".',
      'AI SANCTUARY MAKES NO COMMITMENTS REGARDING THE RELIABILITY, ACCURACY, OR AVAILABILITY OF THE MODELS. DECENTRALIZED NODES CAN AND WILL GO OFFLINE.',
      'WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING FITNESS FOR A PARTICULAR PURPOSE.'
    ]
  },
  {
    id: '09',
    title: 'LIMITATION_OF_LIABILITY',
    body: [
      'IN NO EVENT SHALL AI SANCTUARY, ITS OPERATORS, OR COMMUNITY MEMBERS BE LIABLE FOR ANY INDIRECT, CONSEQUENTIAL, INCIDENTAL, PRIVACY-RELATED, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE OR FROM THE OUTPUT OF THE AI MODELS.'
    ]
  },
  {
    id: '10',
    title: 'MODIFICATIONS',
    body: [
      'We may revise these Terms from time to time. The most current version will always be available on this page. By continuing to access the Services after changes become effective, you agree to be bound by the revised terms.'
    ]
  },
  {
    id: '11',
    title: 'GOVERNING_LAW',
    body: [
      'These Terms shall be governed by the laws of the decentralized internet. In the event of a dispute, arbitration shall be handled informally by designated community adjudicators.'
    ]
  }
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-transparent pt-40 pb-32 font-sans selection:bg-cyan-400 selection:text-black overflow-x-hidden relative z-10">
      
      <div className="container mx-auto px-6 max-w-4xl">
        {/* Hero */}
        <div className="mb-20">
          <div className="inline-flex items-center gap-4 bg-cyan-400 text-black px-6 py-2 font-black uppercase tracking-[0.4em] text-xs shadow-[0_0_15px_rgba(34,211,238,0.3)] mb-12">
            <Shield className="w-4 h-4" />
            PROTOCOL_DOCUMENT_B
          </div>
          <h1 className="text-6xl md:text-8xl font-black text-white mb-8 tracking-tighter uppercase leading-[0.85] italic">
            TERMS_OF_<br />SERVICE
          </h1>
          <p className="text-xl text-slate-400 font-bold uppercase tracking-widest leading-relaxed border-l-4 border-cyan-400 pl-6 max-w-2xl">
            LAST_UPDATED: APRIL 14, 2026<br/>
            EFFECTIVE_IMMEDIATELY
          </p>
        </div>

        {/* Content */}
        <div className="space-y-12">
          {sections.map((section) => (
            <div key={section.id} className="glass-panel p-10 md:p-14 border border-white/10 shadow-[0_10px_30px_rgba(0,0,0,0.5)] group hover:border-cyan-400/50 transition-colors">
              <div className="flex gap-6 items-start">
                <span className="text-cyan-400 font-mono font-black text-xl tracking-tighter mt-1">
                  [{section.id}]
                </span>
                <div>
                  <h2 className="text-3xl font-black text-white uppercase tracking-tighter italic mb-8 group-hover:text-cyan-400 transition-colors">
                    {section.title}
                  </h2>
                  <div className="space-y-6">
                    {section.body.map((para, i) => (
                      <p key={i} className={`text-slate-400 font-bold uppercase ${para.startsWith('•') ? 'text-xs pl-4 border-l-2 border-slate-700' : 'text-sm'} tracking-widest leading-relaxed`}>
                        {para}
                      </p>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Footer info */}
        <div className="mt-20 pt-10 border-t border-white/10 flex flex-col md:flex-row items-center justify-between gap-6">
          <p className="text-slate-500 font-black uppercase text-xs tracking-widest">
            QUESTIONS? TRANSMIT VIA OUR CONTACT NODE.
          </p>
          <Link href="/contact" className="inline-flex items-center gap-2 bg-transparent text-cyan-400 border-2 border-cyan-400 font-black uppercase text-xs tracking-[0.3em] px-8 py-3 hover:bg-cyan-400 hover:text-black transition-all shadow-[0_0_15px_rgba(34,211,238,0.2)]">
            CONTACT_ADMIN <ChevronRight className="w-4 h-4" />
          </Link>
        </div>
      </div>
    </div>
  );
}
